window.LIBRARIAN_CHALLENGE_CONFIG = {
  version: "1.0.0",
  apiBaseUrl: "",
  apiKey: "",
  formspreeUrl: "https://formspree.io/f/xbdvbarg",
  recaptchaSiteKey: "",
  useApiBooks: false,
  maxResultsPerTag: 20,
  autoTag: true,
  bookTags: [
    "Lgbtiq",
    "Queer",
    "Lesbian",
    "Gay",
    "Bisexual",
    "Trans",
    "NonBinary",
    "Intersex",
    "Feminism",
    "Activism",
  ],
};
